#!/bin/ksh
# $MirBSD: wtf,v 1.5 2004/11/02 21:22:02 tg Exp $
# $NetBSD: wtf,v 1.7 2000/11/21 00:18:52 soren Exp $
#-
# Copyright (c) 2004
#	Thorsten "mirabile" Glaser <x86@ePost.de>
#
# Subject to these terms, everybody who obtained a copy of this work
# is hereby permitted to deal in the work without restriction inclu-
# ding without limitation the rights to use, distribute, sell, modi-
# fy, publically perform, give away, merge or sublicence it provided
# this notice is kept and the authors and contributors are given due
# credit in derivates or accompanying documents.
#
# This work is provided "as is" with no explicit or implicit warran-
# ties whatsoever to the maximum extent permitted by applicable law;
# in no event may an author or contributor be held liable for damage
# that is, directly or indirectly, caused by the work, even if advi-
# sed of the possibility of such damage.
#-
# This script was originally in the public domin from NetBSD.

acronyms=${ACRONYMDB:-/usr/share/misc/acronyms}

[[ $1 = is || $1 = ist ]] && shift

[ $# -lt 1 ] && echo "Usage: $(basename $0) [is] <acronym>"

rv=0
while [ $# -gt 0 ] ; do
	target="$(echo "$1" | tr '[:lower:]' '[:upper:]' \
	    | sed 'y/äöü/ÄÖÜ/')"
	ans="$(fgrep "$target" <$acronyms 2>/dev/null \
	    | sed -ne "/^$(echo "$target" \
	    | sed s,/,.,)[[:space:]]/s\`^${target}[[:space:]]*\`\`p")"
	if [[ -z $ans ]]; then
		target="$1"
		ans="$(whatis "$target" 2>/dev/null \
		    | egrep "^${target}[, ]" 2>/dev/null)" \
		 || ans=$(export IFS=\|; fgrep -i "$target" \
		    /usr/ports/INDEX 2>/dev/null \
		    | while read a b c d e; do \
			echo "${a}|${d%% \(uses*}"; done \
		    | fgrep -i "$target" 2>/dev/null \
		    | sort -u \
		    | column -ts'|' \
		)
	fi
	if [[ -n $ans ]]; then
		echo "   ${target}:\n$ans"
	  else
		echo "Gee...  I don't know what '${target}' means..." 1>&2
		rv=1
		if [ -x /usr/bin/dict ]; then
			echo "Let's try The Dictionary..." 1>&2
			rv=2
			dict "$target" && rv=0
		fi
	fi
	shift
done
exit $rv
