.\"	$MirOS: wtf/wtf.1,v 1.5 2011/10/08 19:42:45 tg Exp $
.\"	$NetBSD: wtf.6,v 1.4 2001/04/02 22:42:40 wiz Exp $
.\"-
.\" Copyright © 2002, 2003, 2006, 2010, 2011
.\"	Thorsten Glaser <tg@mirbsd.org>
.\"
.\" Provided that these terms and disclaimer and all copyright notices
.\" are retained or reproduced in an accompanying document, permission
.\" is granted to deal in this work without restriction, including un‐
.\" limited rights to use, publicly perform, distribute, sell, modify,
.\" merge, give away, or sublicence.
.\"
.\" This work is provided “AS IS” and WITHOUT WARRANTY of any kind, to
.\" the utmost extent permitted by applicable law, neither express nor
.\" implied; without malicious intent or gross negligence. In no event
.\" may a licensor, author or contributor be held liable for indirect,
.\" direct, other damage, loss, or other issues arising in any way out
.\" of dealing in the work, even if advised of the possibility of such
.\" damage or existence of a defect, except proven that it results out
.\" of said person’s immediate fault when using the work as intended.
.\"-
.Dd $Mdocdate: October 8 2011 $
.Dt WTF 1
.Os
.Sh NAME
.Nm wtf
.Nd translates acronyms for you
.Sh SYNOPSIS
.Nm
.Op Fl adPpw
.Op is \&| ist
.Ar acronym Ar ...
.Sh DESCRIPTION
The
.Nm
utility displays the expansion of the acronyms
specified on the command line.
The following places are searched:
.Bl -tag -width Ds
.It Fl a
Search the acronym database
.Pq default .
.It Fl d
Search the dictionary.
Needs a dict client installed.
.It Fl P
Search the package database or ports
.Pa INDEX .
Match in package name and description.
.It Fl p
Search the package database or ports
.Pa INDEX .
Match in package name only.
.It Fl w
Search with
.Nm whatis
.Pq default .
.El
.Pp
To disable an option, prefix it with a plus sign
.Pq Sq +
instead of a dash.
.Pp
If
.Dq is
is specified on the command line, it will be ignored,
allowing the fairly natural
.Sy wtf\ is\ WTF
and, for German users,
.Sy wtf\ ist\ Windows
usage.
.Sh ENVIRONMENT
.Bl -tag -width ACRONYMDB
.It Ev ACRONYMDB
The default acronym database may be overridden by setting the
environment variable
.Ev ACRONYMDB
to the name of a file in the proper format (acronym[tab]meaning).
.El
.Sh FILES
.Bl -tag -width /usr/share/misc/acronyms -compact
.It Pa /usr/share/misc/acronyms
default acronym database.
.It Pa /usr/bin/dict
default search path for dictionary client
.It Pa /usr/local/bin/dict
standard search path for dictionary client
.It Pa /usr/mpkg/bin/dict
extended search path for dictionary client
.It Pa /usr/ports/INDEX
default ports index file on BSD.
.El
.Sh SEE ALSO
.Xr whatis 1
.Sh HISTORY
.Nm
first appeared in
.Nx 1.5 .
It then was ported to
.Mx 0 ,
actually being the very reason for MirOS to exist.
Option processing was added in
.Mx 11 .
