.\" $MirOS: wtf/wtf.1,v 1.13 2015/03/13 21:18:22 tg Exp $
.\" $NetBSD: wtf.6,v 1.4 2001/04/02 22:42:40 wiz Exp $
.\"-
.\" Copyright © 2002, 2003, 2006, 2010, 2011, 2012, 2014, 2015
.\"	Thorsten “mirabilos” Glaser <tg@mirbsd.org>
.\"
.\" Provided that these terms and disclaimer and all copyright notices
.\" are retained or reproduced in an accompanying document, permission
.\" is granted to deal in this work without restriction, including un‐
.\" limited rights to use, publicly perform, distribute, sell, modify,
.\" merge, give away, or sublicence.
.\"
.\" This work is provided “AS IS” and WITHOUT WARRANTY of any kind, to
.\" the utmost extent permitted by applicable law, neither express nor
.\" implied; without malicious intent or gross negligence. In no event
.\" may a licensor, author or contributor be held liable for indirect,
.\" direct, other damage, loss, or other issues arising in any way out
.\" of dealing in the work, even if advised of the possibility of such
.\" damage or existence of a defect, except proven that it results out
.\" of said person’s immediate fault when using the work as intended.
.\"-
.\" Try to make GNU groff and AT&T nroff more compatible
.\" * ` generates ‘ in gnroff, so use \`
.\" * ' generates ’ in gnroff, \' generates ´, so use \*(aq
.\" * - generates ‐ in gnroff, \- generates −, so .tr it to -
.\"   thus use - for hyphens and \- for minus signs and option dashes
.\" * ~ is size-reduced and placed atop in groff, so use \*(TI
.\" * ^ is size-reduced and placed atop in groff, so use \*(ha
.\" * \(en does not work in nroff, so use \*(en
.\" * <>| are problematic, so redefine and use \*(Lt\*(Gt\*(Ba
.\" Also make sure to use \& especially with two-letter words.
.\" The section after the "doc" macropackage has been loaded contains
.\" additional code to convene between the UCB mdoc macropackage (and
.\" its variant as BSD mdoc in groff) and the GNU mdoc macropackage.
.\"
.ie \n(.g \{\
.	if \*[.T]ascii .tr \-\N'45'
.	if \*[.T]latin1 .tr \-\N'45'
.	if \*[.T]utf8 .tr \-\N'45'
.	ds <= \[<=]
.	ds >= \[>=]
.	ds Rq \[rq]
.	ds Lq \[lq]
.	ds sL \(aq
.	ds sR \(aq
.	if \*[.T]utf8 .ds sL `
.	if \*[.T]ps .ds sL `
.	if \*[.T]utf8 .ds sR '
.	if \*[.T]ps .ds sR '
.	ds aq \(aq
.	ds TI \(ti
.	ds ha \(ha
.	ds en \(en
.\}
.el \{\
.	ds aq '
.	ds TI ~
.	ds ha ^
.	ds en \(em
.\}
.\"
.\" Implement .Dd with the Mdocdate RCS keyword
.\"
.rn Dd xD
.de Dd
.ie \\$1$Mdocdate: \{\
.	xD \\$2 \\$3, \\$4
.\}
.el .xD \\$1 \\$2 \\$3 \\$4 \\$5 \\$6 \\$7 \\$8
..
.\"
.\" .Dd must come before definition of .Mx, because when called
.\" with -mandoc, it might implement .Mx itself, but we want to
.\" use our own definition. And .Dd must come *first*, always.
.\"
.Dd $Mdocdate: March 13 2015 $
.\"
.\" Check which macro package we use, and do other -mdoc setup.
.\"
.ie \n(.g \{\
.	if \*[.T]utf8 .tr \[la]\*(Lt
.	if \*[.T]utf8 .tr \[ra]\*(Gt
.	ie d volume-ds-1 .ds tT gnu
.	el .ds tT bsd
.\}
.el .ds tT ucb
.\"
.\" Implement .Mx (MirBSD)
.\"
.ie "\*(tT"gnu" \{\
.	eo
.	de Mx
.	nr curr-font \n[.f]
.	nr curr-size \n[.ps]
.	ds str-Mx \f[\n[curr-font]]\s[\n[curr-size]u]
.	ds str-Mx1 \*[Tn-font-size]\%MirOS\*[str-Mx]
.	if !\n[arg-limit] \
.	if \n[.$] \{\
.	ds macro-name Mx
.	parse-args \$@
.	\}
.	if (\n[arg-limit] > \n[arg-ptr]) \{\
.	nr arg-ptr +1
.	ie (\n[type\n[arg-ptr]] == 2) \
.	as str-Mx1 \~\*[arg\n[arg-ptr]]
.	el \
.	nr arg-ptr -1
.	\}
.	ds arg\n[arg-ptr] "\*[str-Mx1]
.	nr type\n[arg-ptr] 2
.	ds space\n[arg-ptr] "\*[space]
.	nr num-args (\n[arg-limit] - \n[arg-ptr])
.	nr arg-limit \n[arg-ptr]
.	if \n[num-args] \
.	parse-space-vector
.	print-recursive
..
.	ec
.	ds sP \s0
.	ds tN \*[Tn-font-size]
.\}
.el \{\
.	de Mx
.	nr cF \\n(.f
.	nr cZ \\n(.s
.	ds aa \&\f\\n(cF\s\\n(cZ
.	if \\n(aC==0 \{\
.		ie \\n(.$==0 \&MirOS\\*(aa
.		el .aV \\$1 \\$2 \\$3 \\$4 \\$5 \\$6 \\$7 \\$8 \\$9
.	\}
.	if \\n(aC>\\n(aP \{\
.		nr aP \\n(aP+1
.		ie \\n(C\\n(aP==2 \{\
.			as b1 \&MirOS\ #\&\\*(A\\n(aP\\*(aa
.			ie \\n(aC>\\n(aP \{\
.				nr aP \\n(aP+1
.				nR
.			\}
.			el .aZ
.		\}
.		el \{\
.			as b1 \&MirOS\\*(aa
.			nR
.		\}
.	\}
..
.\}
.\"-
.Dt WTF 1
.Os
.Sh NAME
.Nm wtf
.Nd translates acronyms for you
.Sh SYNOPSIS
.Nm
.Op Fl adPpw
.Op Fl f Ar dbfile
.Op is \*(Ba ist
.Ar acronym Ar ...
.Sh DESCRIPTION
The
.Nm
utility displays the expansion of the acronyms
specified on the command line.
The following places are searched:
.Bl -tag -width Ds
.It Fl a
Search the acronym database
.Pq default .
.It Fl d
Search the dictionary.
Needs a dict client installed.
.It Fl f Ar dbfile
Overrides the default acronym database, bypassing the value of the
.Ev ACRONYMDB
variable.
.It Fl P
Search the package database or ports
.Pa INDEX .
Match in package name and description.
.It Fl p
Search the package database or ports
.Pa INDEX .
Match in package name only.
.It Fl t Ar arg
Ignored
.Pq for compatibility .
.It Fl w
Search with
.Nm whatis .
.El
.Pp
To disable an option, prefix it with a plus sign
.Pq Sq +
instead of a dash.
.Pp
If any of the
.Fl adPpw
options are given
.Pq set or unset ,
no other or default options are enabled.
.Pp
If
.Dq is
is specified on the command line, it will be ignored,
allowing the fairly natural
.Sy wtf\ is\ WTF
and, for German users,
.Sy wtf\ ist\ n8
usage.
.Pp
The following non-ASCII characters are understood and translated
to their upper-case equivalents or whose case does not matter;
if your search contains any other Unicode characters above U+007E,
you may need to upper-case the search term yourself.
.Dl "ä ö ü ß"
.Sh ENVIRONMENT
.Bl -tag -width ACRONYMDB
.It Ev ACRONYMDB
The default acronym database may be overridden by setting the
environment variable
.Ev ACRONYMDB
to the name of a file in the proper format (acronym[tab]meaning).
.El
.Sh FILES
.Bl -tag -width /usr/share/misc/acronyms -compact
.It Pa /usr/share/misc/acronyms
default acronym database
.It Pa /usr/bin/dict
default search path for dictionary client
.It Pa /usr/local/bin/dict
standard search path for dictionary client
.It Pa /usr/mpkg/bin/dict
extended search path for dictionary client
.It Pa /usr/ports/INDEX
default ports index file on BSD.
.El
.Sh SEE ALSO
.Xr whatis 1
.Pp
.Pa https://www.mirbsd.org/wtf.htm
.No \*(en online acronym database query
.Pp
.Pa https://www.mirbsd.org/acronyms
.No \*(en live updated acronym database
.Sh HISTORY
.Nm
first appeared in
.Nx 1.5 .
It then was ported to
.Mx 0 ,
actually being the very reason for MirOS to exist.
Option processing was added in
.Mx 11 .
.Sh FEEDBACK
.An Thorsten Glaser Aq tg@mirbsd.org
maintains
.Nm
and the acronym database; please send any suggestions to him.
