.\"	$MirOS: wtf/wtf.1,v 1.4 2010/10/01 17:03:59 tg Exp $
.\"	$NetBSD: wtf.6,v 1.4 2001/04/02 22:42:40 wiz Exp $
.\"
.\" Public Domain
.\"
.Dd $Mdocdate: October 1 2010 $
.Dt WTF 1
.Os
.Sh NAME
.Nm wtf
.Nd translates acronyms for you
.Sh SYNOPSIS
.Nm
.Op Fl adpw
.Op is \&| ist
.Ar acronym Ar ...
.Sh DESCRIPTION
The
.Nm
utility displays the expansion of the acronyms
specified on the command line.
The following places are searched:
.Bl -tag -width Ds
.It Fl a
Search the acronym database
.Pq default .
.It Fl d
Search the dictionary.
Needs a dict client installed.
.It Fl p
Search the ports
.Pa INDEX .
.It Fl w
Search with
.Nm whatis
.Pq default .
.El
.Pp
To disable an option, prefix it with a plus sign
.Pq Sq +
instead of a dash.
.Pp
If
.Dq is
is specified on the command line, it will be ignored,
allowing the fairly natural
.Sy wtf\ is\ WTF
and, for German users,
.Sy wtf\ ist\ Windows
usage.
.Sh ENVIRONMENT
.Bl -tag -width ACRONYMDB
.It Ev ACRONYMDB
The default acronym database may be overridden by setting the
environment variable
.Ev ACRONYMDB
to the name of a file in the proper format (acronym[tab]meaning).
.El
.Sh FILES
.Bl -tag -width /usr/share/misc/acronyms -compact
.It Pa /usr/share/misc/acronyms
default acronym database.
.It Pa /usr/bin/dict
default search path for dictionary client
.It Pa /usr/local/bin/dict
standard search path for dictionary client
.It Pa /usr/mpkg/bin/dict
extended search path for dictionary client
.It Pa /usr/ports/INDEX
default ports index file.
.El
.Sh SEE ALSO
.Xr whatis 1
.Sh HISTORY
.Nm
first appeared in
.Nx 1.5 .
It then was ported to
.Mx 0 ,
actually being the very reason for MirOS to exist.
Option processing was added in
.Mx 11 .
